package version

import (
	"bytes"
)

// Application version  -- supplied compile time
var ApplicationVersion string = "0.0.0"

// Build commit -- supplied compile time
var buildCommit string = "0x0000"

// Build time -- supplied compile time
var buildTime string = "Mon Dec 21 13:26:38 UTC 2020"

var RootCmdVersion string = prepareVersionString()

func prepareVersionString() string {
	var buffer bytes.Buffer
	buffer.WriteString(ApplicationVersion + " build " + buildCommit)
	buffer.WriteString("\nCompiled on: " + buildTime)
	// buffer.WriteString("\nConfiguration file version supported: " + CfgVersion)
	return buffer.String()
}

// TODO: Add release file version

var CfgVersion int = 1

// var CfgTemplate string = `
// # -------------------------------------------------------------------------------------------
// # marlinctl root configuration file. Created by Marlin Team for supporting marlinctl runtime.
// #                             DO NOT EDIT THIS FILE MANUALLY
// # The correct way of generating this file is through marlinctl. Run marlinctl clean to generate.
// # Editing this file manually may potentially break marlinctl runtime and subsequent
// # invocations. Do this at your own risk.
// # -------------------------------------------------------------------------------------------

// # Describes the configuration version of marlinctl config file. Marlinctl config_version should match at runtime
// # For example, a marlinctl designed to run with CfgVersion=4 would not play well with config file of version 3
// # Chanage this only when breaking changes are introduced.
// config_version: {{.ConfigVersion}}

// # Describes platforms - linux on x86_86 / Darwin etc. Platforms have specific runtimes - supervisor / systemd etc
// platform: "{{.Platform}}"
// runtime: "{{.Runtime}}"

// # Registry subscription - could be ["rtw", "rtw+beta", "rtw+beta+alpha", "rtw+beta+alpha+dev"]
// registry_subscription: {{.RegistrySubscription}}

// # Registries to pull releases information from
// registry:
//   - rtw:
// 	upstream: "{{.RtwRegistryUpstream}}"
// 	branch: "{{.RtwRegistryBranch}}"
//   - beta:
// 	upstream: "{{.BetaRegistryUpstream}}"
// 	branch: "{{.BetaRegistryBranch}}"
//   - alpha:
// 	upstream: "{{.AlphaRegistryUpstream}}"
// 	branch: "{{.AlphaRegistryBranch}}"
//   - dev:
// 	upstream: "{{.DevRegistryUpstream}}"
// 	branch: "{{.DevRegistryBranch}}"

// # Projects description
// projects:
//   - beacon:
//     version: {{.BeaconVersion}}
// 	subscription: {{.BeaconSubscription}}
//   - relay_iris:
//     version: {{.RelayIrisVersion}}
//     subscription: {{.RelayIrisSubscription}}
//   - gateway_iris:
// 	version: {{.GatewayIrisVersion}}
// 	subscription: {{.GatewayIrisSubscription}}
// `

// marlinctl
//   - cluster
// 	- beacon
// 	  - up
// 	  - down
// 	  - info
// 	  - logs
// 	  - version
// 	  - choose-version
// 	- relay
// 	  - iris // spawns iris relay, abci, spamfilter
// 		- up
// 		- down
// 		- info
// 		- logs
// 		- version
// 		- choose-version
// 	  - near // spawns near relay, abci, spamfilter
// 	    - do
//   - gateway
// 	- iris
//   - registry  // releases registry
//     - update
//   - config   // central cfg
// 	- create
// 	- update
// 	- remove

// marlinctl cluster beacon up
// marlinctl cluster relay iris --version
// marlinctl cluster relay iris choose-version // opens a selection menu
// marlinctl cluster relay iris choose-version --version "0.0.3-alpha.2" // opens a selection menu
// marlinctl cluster relay iris choose-version --include-alpha --include-beta // allows alpha + beta versions to be chosen alongwith public releases
// marlinctl cluster relay iris choose-version --include-dev // internal releases
// marlinctl cluster relay iris up // additional flags can be given

// marlinctl gateway iris choose-version
// marlinctl gateway iris up

// // Version choice (top 20) or search
// -> [REL] 0.0.3 : (Updates to near keyfile generation system)
//    [ALP] 0.0.3-alpha.1 : (keyfile temp checks on)
//    [REL] 0.0.2 : (Connectivity with /tmp/abci_near.sock stablized)
//    [DEV] 0.0.1-dev.20 : (internal abcdefgh)
